book:
  author: Shawn W Laffan
  chapters:
  - index.qmd
  date: '2026-05-05'
  downloads:
  - pdf
  output-file: Biodiverse-publications
  title: Biodiverse publications
editor: source
format:
  html:
    link-external-newwindow: true
    number-sections: false
    theme: zephyr
  pdf:
    number-depth: 2
    number-sections: false
    toc: true
    toc-depth: 3
project:
  output-dir: docs
  type: book
